/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.cresterida.aws

class App {
    val greeting: String
        get() {
            return "Hello world. soy kiquetal"
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
}
